name = "subscription-tracker"
main = "src/index.js"
compatibility_date = "2026-09-27"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/*"]

[[d1_databases]]
binding = "DB"
database_name = "subscription-tracker-db"
database_id = "56ccdfb4-5402-46ee-a903-24f67792d2a8"